package shared;

import java.io.Serial;
import java.io.Serializable;

public record Response(ResponseType RESPONSE_TYPE, String MESSAGE) implements Serializable {
    @Serial
    private static final long serialVersionUID = 2L;

    public enum ResponseType {
        LOGIN_SUCCESS,
        LOGIN_FAILURE,
        CREATE_USER_SUCCESS,
        CREATE_USER_FAILURE,
        SEARCH_SUCCESS,
        SEARCH_FAILURE;
        // ADD_TO_CART_SUCCESS,
        // ADD_TO_CART_FAILURE,
        // REMOVE_FROM_CART_SUCCESS,
        // REMOVE_FROM_CART_FAILURE,
        // CHECKOUT_SUCCESS,
        // CHECKOUT_FAILURE,
        // GET_CART_SUCCESS,
        // GET_CART_FAILURE,
        // GET_PURCHASE_HISTORY_SUCCESS,
        // GET_PURCHASE_HISTORY_FAILURE,
        // GET_PRODUCT_SUCCESS,
        // GET_PRODUCT_FAILURE,
        // GET_PRODUCT_LIST_SUCCESS,
        // GET_PRODUCT_LIST_FAILURE,
        // GET_USER_SUCCESS,
        // GET_USER_FAILURE,
        // GET_USER_LIST_SUCCESS,
        // GET_USER_LIST_FAILURE,
        // GET_USER_PURCHASE_HISTORY_SUCCESS,
        // GET_USER_PURCHASE_HISTORY_FAILURE,
        // GET_USER_CART_SUCCESS,
        // GET_USER_CART_FAILURE,
        // GET_USER_CART_TOTAL_SUCCESS,
        // GET_USER_CART_TOTAL_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_AND_USER_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_AND_USER_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_AND_USER_AND_USER_LIST_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_AND_USER_AND_USER_LIST_FAILURE,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_AND_USER_AND_USER_LIST_AND_USER_SUCCESS,
        // GET_USER_CART_TOTAL_COUNT_AND_TOTAL_AND_CART_AND_PURCHASE_HISTORY_AND_PRODUCT_LIST_AND_PRODUCT_AND_USER_AND_USER_LIST_AND_USER_FAILURE;
    }
}
